### PR TITLE
Enhance and refactor rules.

### LINKED ISSUE #83: False error with "continue"
# from Richard

> Bug report: The editor thinks that "continue" is a separate verb. "You(children) continue to carefully consider that message" is marked as an error.

### PR DESCRIPTION
**Pull request by craigp-atw**
### Enhance and refactor rules.
- support searching within subtokens
- support use of shorthand 'skip groups'
- move some `syntax_rules` into more logical places

### Added/updated several rules
- tag patient clauses more accurately (`quote_begin`, `same_subject`, or `stand_alone`)

- support `begin` along with `start`
image

- Fix #83 with use of skip groups
image

### Support improved how-to lookup.
- Show warning that a word is not yet in the ontology but should be soon (could this be the first use-case of an 'info' message?)
image
image

- support the improved api for the how-to lookup
image
image

- don't remove all other senses when selecting a sense via rules
-- Created #84 to handle a user-specified sense
image

### CODE REVIEW

File: app/src/lib/lookups.js [hunk 1]
```diff
@@ -1,4 +1,7 @@
-import { TOKEN_TYPE, concept_with_sense, split_stem_and_sense } from './parser/token'
+import { TOKEN_TYPE, split_stem_and_sense } from './parser/token'
```
Comment (longrunningprocess) [inline app/src/lib/lookups.js:1]: these imports really tell a cohesive story about what is going to happen in this file, great sign!

File: app/src/lib/lookups.js [hunk 2]
```diff
@@ -142,21 +147,32 @@ async function check_ontology(lookup_token) {
...
+		} else if (how_to_result.sense) {
+			// The sense exists in the how-to but not in the ontology, but is planned to be added
+			const new_result = create_lookup_result(how_to_result, { how_to: [how_to_result] })
+			new_result.concept = {
+				id: '0',
+				stem: new_result.stem,
+				sense: how_to_result.sense,
+				part_of_speech: new_result.part_of_speech,
+				level: 2,		// since it's in the how-to, it's expected to be complex
+				gloss: 'Not yet in Ontology (but should be soon)',
```
Comment (longrunningprocess) [inline app/src/lib/lookups.js:169]: nice!

File: app/src/lib/parser/clausify.js
Comment (longrunningprocess) [inline app/src/lib/parser/clausify.js:1]: this reads much better now, good call on the refactor

File: app/src/lib/parser/index.js [hunk 3]
```diff
@@ -2,7 +2,7 @@ import { pipe } from '$lib/pipeline'
 import { tokenize_input } from './tokenize'
 import { perform_form_lookups, perform_ontology_lookups } from '$lib/lookups'
 import { clausify, flatten_sentences } from './clausify'
-import { CHECKER_RULES, LOOKUP_RULES, PART_OF_SPEECH_RULES, SYNTAX_RULES, TRANSFORM_RULES, PRONOUN_RULES, rules_applier } from '$lib/rules'
+import { RULES, rules_applier } from '$lib/rules'
```
Comment (longrunningprocess) [inline app/src/lib/parser/index.js:5]: thank you, I like that much better 🧹

File: app/src/lib/parser/token.js [hunk 4]
```diff
@@ -99,8 +100,11 @@ export function set_token_concept(token, concept) {
 	}
 
 	const { stem, sense } = split_stem_and_sense(concept)
-	token.lookup_terms = [concept]
-	token.lookup_results = token.lookup_results.filter(result => result.stem === stem && result.concept?.sense === sense)
+	const concept_index = token.lookup_results.findIndex(result => result.stem === stem && result.concept?.sense === sense)
+	const selected_result = token.lookup_results.splice(concept_index, 1)
+
+	// put the selected sense at the top
+	token.lookup_results = [...selected_result, ...token.lookup_results]
```
Comment (longrunningprocess) [inline app/src/lib/parser/token.js:107]: very user-focused, thank you!

File: app/src/lib/rules/index.js
Comment (longrunningprocess) [inline app/src/lib/rules/index.js:1]: 🌟

File: app/src/lib/rules/syntax_rules.js
Comment (longrunningprocess) [inline app/src/lib/rules/syntax_rules.js:1]: wow, pretty extraordinary refactor here, excellent!

**Review by longrunningprocess — APPROVED** [review]
this is a GREAT refactor, nice work!
